# Определяем переменные для аргументов
ARGS1 = Hello World
ARGS2 = Makefile Example
ARGS3 = Sequential Execution

# Цель по умолчанию
all: program1 program2 program3

# Цель program1
program1:
	@echo "Running program1 with args: $(ARGS1)"
	python program1.py

# Цель program2
program2:
	@echo "Running program2 with args: $(ARGS2)"
	python program2.py

# Цель program3
program3:
	@echo "Running program3 with args: $(ARGS3)"
